src/Entity/Avis.php
<?php

namespace App\Entity;

use App\Repository\AvisRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AvisRepository::class)]
class Avis
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column]
    private ?int $codePostal = null;

    #[ORM\Column(length: 255)]
    private ?string $suject = null;

    #[ORM\Column]
    private ?int $point = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->codePostal;
    }

    public function setCodePostal(int $codePostal): self
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    public function getSuject(): ?string
    {
        return $this->suject;
    }

    public function setSuject(string $suject): self
    {
        $this->suject = $suject;

        return $this;
    }

    public function getPoint(): ?int
    {
        return $this->point;
    }

    public function setPoint(int $point): self
    {
        $this->point = $point;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Repository\CommandeRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProfilController extends AbstractController
{
   
    #[Route('/profil', name: 'profil')]
    public function index(CommandeRepository $repo): Response
    {
        $coms = $repo->findBy(['user' => $this->getUser()]);

        return $this->render('profil/index.html.twig', [
            'coms' => $coms
        ]);
    }
}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProfilController!
{% endblock %}

{% block body %}
  
	{% if coms %}

		<table class="table">
			<thead>
				<tr>
					<th>Produit</th>
					<th>Description</th>
					<th>Quantité</th>
					<th>Etat</th>
					<th>Date d'achat</th>
					<th>Montant</th>
				</tr>
			</thead>
			<tbody>
				{% for item in coms %}
					<tr>
						<td>{{ item.produit.titre }}</td>
						<td>{{ item.produit.description|raw }}</td>
						<td>{{ item.quantite }}</td>
						<td>{{ item.etat }}</td>
						<td>{{ item.dateEnregistrement|date('d/m/Y à H:i:s') }}</td>
						<td>{{ item.montant / 100|number_format(2) }}€</td>
						
					</tr>
				{% endfor %}
			</tbody>
		</table>

	{% else %}
		<p>Vous n'avez pas encore passé commande chez nous !</p>
	{% endif %}

{% endblock %}